config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "pages#home"

  resources :floaties, only: [:index, :show, :new, :create] do
    resources :reviews, only: :create
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index]

  get "floatiesmap", to: "pages#map_all"
  get "my_floaties", to: "floaties#my_floaties"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :floaty
end

app/models/floaty.rb
class Floaty < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :floaty
  validates :comment, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :floaties
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  :omniauthable, omniauth_providers: %i[facebook]

#   def self.new_with_session(params, session)
#     super.tap do |user|
#       if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
#         user.email = data["email"] if user.email.blank?
#       end
#     end
#   end

#   def self.from_omniauth(auth)
#     name_split = auth.info.name.split(" ")
#     user = User.where(email: auth.info.email).first
#     user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[0], first_name: name_split[1], email: auth.info.email, password: Devise.friendly_token[0, 20])
#       user
#   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    user = current_user
    @bookings = Booking.where(user_id: user.id)
  end

  def new
    @floaty = Floaty.find(params[:floaty_id])
    @booking = Booking.new
  end

  def create
    @floaty = Floaty.find(params[:floaty_id])
    @booking = Booking.new(booking_params)
    @booking.floaty = @floaty
    @booking.user = current_user
    if @booking.save
      redirect_to floaty_path(@floaty)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/floaties_controller.rb
class FloatiesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def my_floaties
    @floaties = Floaty.geocoded.where(user_id: current_user.id)
  end

  def index
    @floaties = Floaty.geocoded

    if params[:query].present?
      sql_query = "title ILIKE :query OR category ILIKE :query OR address ILIKE :query"
      @floaties = Floaty.geocoded.where(sql_query, query: "%#{params[:query]}%")
    else
      @floaties = Floaty.geocoded
    end
  end

  def show
    @floaty = Floaty.find(params[:id])
    @review = Review.new
    @markers = [{
      lat: @floaty.latitude,
      lng: @floaty.longitude,
      info_window: render_to_string(partial: "info_window", locals: { floaty: @floaty })
      # image_url: helpers.asset_url("quaqua.png")
    }]
  end

  def new
    @floaty = Floaty.new
  end

  def create
    @floaty = Floaty.new(floaty_params)
    @floaty.user = current_user
    if @floaty.save
      redirect_to floaty_path(@floaty)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def floaty_params
    params.require(:floaty).permit(:title, :category, :details, :price, :city, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @floaties = Floaty.geocoded
    if params[:query].present?
      sql_query = "title ILIKE :query OR category ILIKE :query OR address ILIKE :query"
      @floaties = Floaty.geocoded.where(sql_query, query: "%#{params[:query]}%")
    else
      @floaties = Floaty.geocoded
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'list', formats: :html, locals: { floaties: @floaties } }
    end
  end

  def map_all
    @floaties = Floaty.geocoded
    # The `geocoded` scope filters only flats with coordinates
    @markers = @floaties.map do |floaty|
      {
        lat: floaty.latitude,
        lng: floaty.longitude,
        info_window: render_to_string(partial: "floaties/info_window", locals: { floaty: floaty }),
        # image_url: helpers.asset_url("quaqua.png")
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @floaty = Floaty.find(params[:list_id])
    @review.floaty = @floaty
    respond_to do |format|
      if @review.save
        format.html { redirect_to floaty_path(@floaty) }
        format.json
      else
        format.html { render "floaties/show", status: :unprocessable_entity }
        format.json
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :stars)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller_.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/floaties/_review.html.erb
<p><%= @review.comment %></p>

app/views/floaties/my_floaties.html.erb
<div>
  <%# NAVBAR %>
  <%= render "shared/navbar" %>
</div>
<div>

  <div class="container container_myfloaties">
    <%# Total of reservations %>
    <div class="col-12 d-flex align-items-center justify-content-between">
      <h4 class="list_count"><%= @floaties.count %> Listings</h4>
      <%= link_to "Add new floatie", new_floaty_path %>
    </div>


    <div class="row d-flex align-items-center justify-content-between">
      <%# HEADER %>
      <div class="col-2"></div>
      <div class="col-2 floaty_info_head ">TITLE</div>
      <div class="col-2 floaty_info_head ">STATUS</div>
      <div class="col-2 floaty_info_head ">LOCATION</div>
      <div class="col-2 floaty_info_head ">LAST MODIFIED</div>
      <%= link_to root_path do %>
        <div class="col-1 floaty_info_head ">EDIT</div>
      <% end %>
      <div class="col-12">
        <hr class="divider">
      </div>
    </div>

    <% @floaties.each do |floaty| %>
      <%# Retrive city name from coordinates %>
      <% lat = floaty.latitude %>
      <% lon = floaty.longitude %>
      <% lat_lon = "#{lat},#{lon}" %>
      <% response = Geocoder.search(lat_lon).first %>
      <% city =  response.city if response.present?%>

      <%# Myfloaty row %>
      <div class="row align-items-center d-flex justify-content-between">
        <div class="col-2">
          <div class="my_floaty-card">
            <% if floaty.photos.attached? %>
              <img src=" <%= cl_image_path floaty.photos.first.key %> " class="d-block w-100" alt="...">
            <% else %>
              No photo
            <% end %>
          </div>
        </div>
        <div class="col-2 floaty_info">
          <%= floaty.title %>
        </div>
        <div class="col-2 floaty_info">
          <% if floaty.listed == true %>
            <i class="fa-solid fa-location-dot green"></i><span>&nbsp&nbsp&nbspListed</span>
          <% else %>
            <i class="fa-solid fa-location-dot red"></i><span>&nbsp&nbsp&nbspUnlisted</span>
          <% end %>
        </div>
        <div class="col-2 floaty_info">
          <%= city %>
        </div>
        <div class="col-2 floaty_info">
          <%= floaty.updated_at.strftime("%b %d %Y")%>
        </div>
        <div class="col-1">
          <i class="fa-solid fa-pen-to-square"></i>
        </div>
      </div>

      <%# DIVIDER  %>
      <div class="col-12">
        <hr class="divider">
      </div>


    <% end %>

  </div>
</div>

app/views/floaties/show.html.erb
<div>
  <%# NAVBAR %>
  <%= render "shared/navbar" %>
</div>
<div class=" container_myfloaties">
    <div class="row">
    <div class="col-1">
    </div>

    <div class="col-lg-6 mr-5">
        <div class="card-floaty-show justify-content-between d-flex align-items-center my-4 mt-5">
            <div>
            <h3><strong><%= @floaty.category %></strong> for <strong>€<%= @floaty.price %></strong> /day</h3>
            <p>Location: <%= @floaty.address %></p>
            </div>
            <div>
            <%= link_to "Reserve", new_floaty_booking_path(@floaty), class:"btn btn-flat-show" %>
            </div>
        </div>

        <div class="card-floaty-show carousel slide" id="carouselExampleControls" data-bs-ride="carousel">
        <div class="carousel-inner">
            <% if @floaty.photos.attached? %>
            <div class="carousel-item active">
                <%= cl_image_tag @floaty.photos.first.key, class:"d-block w-100", height: 300, width: 400, crop: :fill %>
            </div>
            <% @floaty.photos.drop(1).each do |photo| %>
                <div class="carousel-item">
                <%= cl_image_tag photo.key, class:"d-block w-100", height: 300, width: 400, crop: :fill %>
                </div>
            <% end %>
            <% else %>
            <div class="carousel-item active">
                <%= image_tag "rubber_duck.jpg", class:"d-block w-100", height: 300, width: 400, crop: :fill %>
            </div>
            <% end %>
        </div>

        <% if @floaty.photos.count > 1 %>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
        <% end %>
        </div>

        <div class="card-floaty-show-text">
        <h3><%= @floaty.title %></h3>
        <p>"<%= @floaty.details %>"</p>
        </div>

        <div class="card-review">
        <div class="card-floaty-show d-flex justify-content-between my-4 mt-3">
            <div class="d-flex align-items-start">
            <i class="fa-solid fa-star"></i>
            <h3><strong><%= pluralize @floaty.reviews.size, "review" %></strong></h3>
            </div>
            <div>
            <%= link_to "New Review", floaty_reviews_path(@floaty), class:"btn btn-flat-review" %>
            </div>
        </div>

        <div data-controller="insert-in-list">
            <div data-insert-in-list-target="items">
            <% if @floaty.reviews.blank? %>
                Be the first to leave a review for <%= @floaty.title %>
            <% else %>
                <% @floaty.reviews.each do |review| %>
                <p><%= review.comment %></p>
                <% end %>
            <% end %>
            <div>
            <%= render "review" %>
            </div>
            </div>
        </div>
        </div>
        <div class="d-flex justify-content-center m-5">
        <%= link_to "See more floaties!", floaties_path, class:"btn btn-flat-text" %>
        </div>
    </div>
    <div class="col-1">
    </div>

    <div class="col-4 map">
        <%= render "map_show" %>
    </div>
    </div>
</div>
<%# FOOTER %>
<%= render "shared/footer" %>

app/views/floaties/show_.html.erb
<div>
  <%# NAVBAR %>
  <%= render "shared/navbar" %>
</div>
<div>
<div class="container container_myfloaties">
    <div class="row">
        <div class="col-lg-6 mr-5">
            <div class="card-floaty-show justify-content-between d-flex align-items-center my-4 mt-5">
                <div>
                    <h3><strong><%= @floaty.category %></strong> for <strong>€<%= @floaty.price %></strong> /day</h3>
                    <p>Location: <%= @floaty.address %></p>
                </div>
                <div>
                    <%= link_to "Reserve", new_floaty_booking_path(@floaty), class:"btn btn-flat-show" %>
                </div>
            </div>

            <div class="card-floaty-show carousel slide" id="carouselExampleControls" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <% if @floaty.photos.attached? %>
                        <div class="carousel-item active">
                            <%= cl_image_tag @floaty.photos.first.key, class:"d-block w-100", height: 300, width: 400, crop: :fill %>
                        </div>
                        <% @floaty.photos.drop(1).each do |photo| %>
                            <div class="carousel-item">
                            <%= cl_image_tag photo.key, class:"d-block w-100", height: 300, width: 400, crop: :fill %>
                            </div>
                        <% end %>
                    <% else %>
                        <div class="carousel-item active">
                            <%= image_tag "rubber_duck.jpg", class:"d-block w-100", height: 300, width: 400, crop: :fill %>
                        </div>
                    <% end %>
                </div>

                <% if @floaty.photos.count > 1 %>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                    </button>
                <% end %>
            </div>

            <div class="card-floaty-show-text">
                <h3><%= @floaty.title %></h3>
                <p>"<%= @floaty.details %>"</p>
            </div>

            <div class="card-review">
                <div class="card-floaty-show d-flex justify-content-between my-4 mt-3">
                    <div class="d-flex align-items-start">
                    <i class="fa-solid fa-star"></i>
                    <h3><strong><%= pluralize @floaty.reviews.size, "review" %></strong></h3>
                    </div>
                    <div>
                    <%= link_to "New Review", floaty_reviews_path(@floaty), class:"btn btn-flat-review" %>
                    </div>
                </div>

                <div data-controller="insert-in-list">
                    <div data-insert-in-list-target="items">
                    <% if @floaty.reviews.blank? %>
                        Be the first to leave a review for <%= @floaty.title %>
                    <% else %>
                        <% @floaty.reviews.each do |review| %>
                        <p><%= review.comment %></p>
                        <% end %>
                    <% end %>
                    <div>
                    <%= render "review" %>
                    </div>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-center m-5">
                <%= link_to "See more floaties!", floaties_path, class:"btn btn-flat-text" %>
            </div>
        </div>
        <div class="col-6 mr-5">
            <div class="card-floaty-show justify-content-between d-flex align-items-center my-4 mt-5">
            </div>
            <div class="col-4 map">
                 <%= render "map_show" %>
            </div>

            <div>
            </div>
            <div>
            </div>

            <div class="card-floaty-show-text">

            </div>
        </div>

    </div>
</div>

<%# FOOTER %>
<%= render "shared/footer" %>

app/views/pages/home_old.html.erb
<html>
  <%# BANNER %>
  <div class="landing-bck-img">
    <%# NAVBAR %>
    <%= render "shared/navbar" %>

    <%# TYPRSCRIPT %>
    <div class="type-text" >
      <h1><span data-controller="typed-js"></span></h1>
    </div>

    <%# SEE MAP BUTTON %>
    <%= link_to floatiesmap_path do %>
      <div class="map-list-button">
          <div>
            <h3>See map</h3>
          </div>
          <div>
            <i class="fa-regular fa-map symbol"></i>
          </div>
      </div>
    <% end %>
  </div>

  <%# SEARCH CARD GRID %>
  <div class="floaties-grid">
    <div data-togglemap-target="grid" class="container">
      <div class="card-grid-title">
        <% if params[:query] %>
          <h2>Float around...<%= " " + params[:query] + "!" %></h2>
        <% else %>
          <h2>Float around... the world!  <%= params[:query] %></h2>
        <% end %>
      </div>

      <div class="card-grid">
        <% @floaties.each do |floaty| %>
          <%= link_to floaty_path(floaty), :class => "card-floaty" do %>

            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-interval="false">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src=" <%= cl_image_path floaty.photos.first.key %> " class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="..." class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                  <img src="..." class="d-block w-100" alt="...">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>

            <div class="d-flex justify-content-between align-itmes-center">
              <div>
                <h3><%= floaty.title %></h3>
                <p>Rent me in for €<%= floaty.price %></p>
              </div>
            </div>

          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</html>

app/views/shared/_navbar.html copy.erb
<nav class="navbar sticky-top bg-body-tertiary">
  <div class="container-fluid justify-content-between">
    <%= link_to "/", class: "navbar-brand navbar-logo" do %>
      <%= image_tag "logo_floaty.png" %>
    <% end %>

    <div class="navbar-search_form ">
      <%= render "shared/search_form" %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= new_floaty_path %>">Rent my floatie</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-bars dropbtn"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <% if user_signed_in? %>
              <li><%= link_to "Messages", bookings_path, class:"dropdown-item" %></li>
              <li><%= link_to "Notifications", bookings_path, class:"dropdown-item" %></li>
              <li><%= link_to "My reservations", bookings_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Rent a new floaty", new_floaty_path, class:"dropdown-item" %></li>
              <li><%= link_to "Manage my floaties", my_floaties_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign-out", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign-in", bookings_path, class:"dropdown-item" %></li>
              <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar nabbar_bg fixed-top navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid my-2">
        <div>
            <%# Logo  %>
            <%= link_to "/", class: "navbar-brand navbar-logo" do %>
                <%= image_tag "logo_floaty.png" %>
            <% end %>
        </div>

        <div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Menu
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                        <% if user_signed_in? %>
                            <li><%= link_to "Messages", bookings_path, class:"dropdown-item" %></li>
                            <li><%= link_to "Notifications", bookings_path, class:"dropdown-item" %></li>
                            <li><%= link_to "My reservations", bookings_path, class:"dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to "Rent new floaty", new_floaty_path, class:"dropdown-item" %></li>
                            <li><%= link_to "Manage my floaties", my_floaties_path, class:"dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to "Sign-out", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item" %></li>
                        <% else %>
                            <li><%= link_to "Sign-in", new_user_registration_path, class:"dropdown-item" %></li>
                            <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
                        <% end %>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

app/views/shared/_navbar_.html.erb
<nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand navbar-logo" do %>
      <%= image_tag "logo_floaty.png" %>
    <% end %>
    <div class="navbar-search_form">
      <%= render "shared/search_form" %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= new_floaty_path %>">Rent my floatie</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-bars dropbtn"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <% if user_signed_in? %>
              <li><%= link_to "Messages", bookings_path, class:"dropdown-item" %></li>
              <li><%= link_to "Notifications", bookings_path, class:"dropdown-item" %></li>
              <li><%= link_to "My reservations", bookings_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Rent a new floaty", new_floaty_path, class:"dropdown-item" %></li>
              <li><%= link_to "Manage my floaties", my_floaties_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign-out", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign-in", bookings_path, class:"dropdown-item" %></li>
              <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar_home.html.erb
<nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary"
        <%# data-controller="navbar" %>
        data-action="scroll@window->navbar#updateNavbar"
        data-navbar-target="navbar">

    <div class="container-fluid my-2">
        <div>
            <%# Logo  %>
            <%= link_to "/", class: "navbar-brand navbar-logo" do %>
                <%= image_tag "logo_floaty.png" %>
            <% end %>
        </div>

        <div class="navbar-search_form">
            <%= render "shared/search_form" %>
        </div>

        <div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Menu
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                        <% if user_signed_in? %>
                            <li><%= link_to "Messages", bookings_path, class:"dropdown-item" %></li>
                            <li><%= link_to "Notifications", bookings_path, class:"dropdown-item" %></li>
                            <li><%= link_to "My reservations", bookings_path, class:"dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to "Rent new floaty", new_floaty_path, class:"dropdown-item" %></li>
                            <li><%= link_to "Manage my floaties", my_floaties_path, class:"dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item" %></li>
                        <% else %>
                            <li><%= link_to "Sign-up", new_user_registration_path, class:"dropdown-item" %></li>
                            <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
                        <% end %>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>